"""
	PARA FAZER A LLISTAGEM DE DADOS É TRANQUILO, 

	JÁ PARA FAZER A LISTAGEM DE IMAGENS JÁ É MAIS COMPLICADO, PARA TAL TAREFA
	TEMOS IMPORTAR ALGUNS ARQUIVOS E FAZER ALGUMAS ALTERAÇÕES.

	ARQUIVOS:
	#urls  --> tem que ser o principal



"""