# -*- coding: utf-8 -*-
__author__ = 'Junior Lima'
"""
Django settings for tiago project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')gjt%-qdcmiw#1*zk-bs9b&vqvr5flebgw)*#gni2a5!=l8t+u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'easy_thumbnails',
    'filer',
    'mptt',

    'atendimento',
    'contato',
    'core',
    'gabinete',
    'informacao',
    'portal',
    'votacao',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tiago.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tiago.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tiago',
        'USER': 'root',
        'PASSWORD': 'passDigital02',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'pt_BR'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# JET CONFIGS
JET_DEFAULT_THEME = 'default'
JET_SIDE_MENU_COMPACT = True
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M',]
DATE_INPUT_FORMATS = ['%d/%m/%Y',]
TIME_INPUT_FORMATS = ['%H:%M',]
# CK Editor
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'Basic',
    },
    'default': {
        'toolbar': 'full',
        'height': 600,
        'width': '100%',
    },
    'junior_lima': {
        'toolbar': [
            [
                'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord',
                '-', 'Undo', 'Redo',
                '-', 'Find', 'Replace',
                '-', 'SelectAll',
                '-', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript',
                '-', 'RemoveFormat',
                '-', 'NumberedList', 'BulletedList',
                '-', 'Blockquote',
                '/',
                '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock',
                '-', 'Link', 'Unlink',
                '-', 'Image', 'HorizontalRule', 'Smiley', 'SpecialChar', 'Iframe',
                '-', 'Maximize', 'ShowBlocks',
                '-', 'Source'
            ],
        ],
        'height': 300,
        'width': '70%',
    }
    # https://github.com/django-ckeditor/django-ckeditor
}

# EASY THUMBNAILS
THUMBNAIL_ALIASES = {
    '': {
        'noticia_750_523': {'size': (750,0), 'crop': True},
        'noticia_360_245': {'size': (360,245), 'crop': True},
    },
}

# Local settings
try:
   from local_settings import *
except ImportError, e:
   pass

#Django Filer
FILER_CANONICAL_URL = 'imagens/'