<?php 
$acao=$_GET['acao'];
$id=$_GET['id'];
switch ($acao){
	case 'formcadastroentrada':
	$form=new Form("entrada");
	$form->FormCadastro('produto','entrada','categoria,produto,fornecedor',
	array('remetentecategoria'=>'categoria','destinatariocategoria'=>'produto','tabelacategoria'=>'produto'
	));//,'remetenteproduto'=>'produto','destinatarioproduto'=>'fornecedor','tabelaproduto'=>'fornecedor'));	
	break;
	
	case 'formcadastrosaida':
	$form=new Form("saida");
	$form->FormCadastro('produto','saida','produto,retirante,categoria',array('remetentecategoria'=>'categoria','destinatariocategoria'=>'produto','tabelacategoria'=>'produto'));	
	break;
	
	
}


?>